controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_velocity_controller:
  ros__parameters:
    joints:
      - wheel_fl_joint
      - wheel_fr_joint
      - wheel_rl_joint
      - wheel_rr_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - effort
      - velocity

forward_position_controller:
  ros__parameters:
    joints:
      - swerve_fl_joint
      - swerve_fr_joint
      - swerve_rl_joint
      - swerve_rl_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - effort
      - velocity
